spring.application.name=rest

spring.datasource.url=jdbc:postgresql://localhost:5432/library
spring.datasource.username=root
spring.datasource.password=123

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
#spring.jpa.database-platform=org.hibernate.dialect.PostgresSQL10Dialect

debug=true

spring.main.web-application-type=SERVLET
spring.jpa.hibernate.ddl-auto = update

spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
